app:
  vbank-base-url: ${V_BANK_BASE_URL}
  abank-base-url: ${A_BANK_BASE_URL}
  sbank-base-url: ${S_BANK_BASE_URL}
  client-id: ${SANDBOX_CLIENT_ID}
  client-secret: ${SANDBOX_CLIENT_SECRET}

server:
  port: 8080

spring:
  thymeleaf:
    cache: false
